all: ./main.cpp ./src/BunuriServicii.cpp ./src/Data.cpp ./src/Plata.cpp ./src/GestionareCheltuieli.cpp
	g++ -o ./bin/Debug/proiect_poo_v1 -I./include ./main.cpp ./src/GestionareCheltuieli.cpp ./src/BunuriServicii.cpp ./src/Data.cpp ./src/Plata.cpp 
run:
	./bin/Debug/poiect_poo_v1
clean:
	rm -f ./bin/*
clean(win):
	del /f bin\*